limericks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('limerines.urls'))
]

limerines/urls.py
from django.urls import path

from . import views

app_name = 'limerines'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('limericks/', views.all_limericks, name='limericks'),
    path('generate/', views.generate_limerick, name='generate'),
    path('limericks/<int:limerick_id>', views.detail, name='detail'),
    path('limericks/<int:limerick_id>/edit', views.detail, name='edit'),
    path('limericks/<int:limerick_id>/edit/result', views.detail, name='result'),
]

limerines/forms.py
from django import forms
from django.db.utils import OperationalError

try:
    from .models import AdjProfHelper
    try:
        ADJECTIVE_CHOICES = AdjProfHelper.object().adjectives_list
        PROFESSION_CHOICES = AdjProfHelper.object().profession_list
    except:
        ADJECTIVE_CHOICES = []
        PROFESSION_CHOICES = []
except OperationalError:
    ADJECTIVE_CHOICES = []
    PROFESSION_CHOICES = []
    
GENDER_CHOICES = (('All','All'),('female','Female'),('male','Male'))
TYPE_CHOICES = (('All','All'),('name','Name'),('place','Place'))
KIND_CHOICES = (('single','single'),('multiple', 'multiple'))
SORT_CHOICES = (('user','user'),('model', 'model'))


class LimerickForm(forms.Form):
    adjective = forms.ChoiceField(choices = ADJECTIVE_CHOICES)
    profession = forms.ChoiceField(choices = PROFESSION_CHOICES)
    kind = forms.ChoiceField(choices = KIND_CHOICES)

class VoteForm(forms.Form):
    limerick_id = forms.IntegerField()
    upvote = forms.ChoiceField(choices = [('true','true'),('false','false')])

class FilterForm(forms.Form):
    adjective = forms.ChoiceField(choices = [('All','All')] + ADJECTIVE_CHOICES)
    profession = forms.ChoiceField(choices = [('All','All')] + PROFESSION_CHOICES)
    gender = forms.ChoiceField(choices = GENDER_CHOICES)
    type = forms.ChoiceField(choices = TYPE_CHOICES)
    sort = forms.ChoiceField(choices = SORT_CHOICES)

class SaveLimerickForm(forms.Form):
    verse1 = forms.CharField(max_length=100)
    verse2 = forms.CharField(max_length=100)
    verse3 = forms.CharField(max_length=100)
    verse4 = forms.CharField(max_length=100)
    verse5 = forms.CharField(max_length=100)
    overse1 = forms.CharField(max_length=100)
    overse3 = forms.CharField(max_length=100)
    overse4 = forms.CharField(max_length=100)
    overse5 = forms.CharField(max_length=100)
    adjective = forms.CharField(max_length=100)
    profession = forms.CharField(max_length=100)
    female = forms.BooleanField(required=False)
    place = forms.BooleanField(required=False)

limerines/views.py
import random
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import resolve

from django.db.utils import OperationalError
try:

    from .forms import FilterForm, LimerickForm, ADJECTIVE_CHOICES, SaveLimerickForm, VoteForm

    from .models import Limerick, AdjProfHelper, generateFromSecond, generateFromThird, generateFromFourth, run_limerick_generation_multiple, run_limerick_generation_single, update_rankings


    def indexView(request):
        # reset session in home page
        try:
            del request.session['limericks']
        except KeyError:
            pass
        try:
            del request.session['new_limerick']
        except KeyError:
            pass
        try:
            del request.session['originating']
        except KeyError:
            pass
        try:
            del request.session['filtered_limericks']
        except KeyError:
            pass
        try:
            del request.session['sort']
        except KeyError:
            pass
        return render(request, 'limerines/index.html')

    def all_limericks(request):
        # reset session in all limericks
        try:
            del request.session['limericks']
        except KeyError:
            pass
        try:
            del request.session['originating']
        except KeyError:
            pass
        try:
            del request.session['new_limerick']
        except KeyError:
            pass
        sort = 'user'
        try:
            sort = request.session['sort']
        except KeyError:
            pass

        if request.method == "POST":
            filter_form = FilterForm(request.POST) # check if filtering all limericks is valid
            if 'limerick_id' in request.POST: # if Post request contains a limerick, then it is an upvote/downvote request
                form = VoteForm(request.POST)
                if form.is_valid():
                    upvote = form.cleaned_data.get('upvote')
                    limerick_id = form.cleaned_data.get('limerick_id')
                    l = Limerick.objects.get(pk=limerick_id)
                    if upvote == 'true':
                        l.votes += 1
                    elif upvote == 'false':
                        l.votes -= 1
                    l.save()
                    update_rankings() # update all rankings after voting
            if filter_form.is_valid():
                gender = filter_form.cleaned_data.get('gender')
                adjective = filter_form.cleaned_data.get('adjective')
                profession = filter_form.cleaned_data.get('profession')
                type = filter_form.cleaned_data.get('type')
                sort = filter_form.cleaned_data.get('sort')
                limericks = Limerick.objects.all()

                #get all filtered limericks by the fields specified by the user
                if gender == 'male':
                    limericks = limericks.filter(female=False)
                elif gender == 'female':
                    limericks = limericks.filter(female=True)
                if adjective != 'All':
                    limericks = limericks.filter(adjective=adjective)
                if profession != 'All':
                    limericks = limericks.filter(profession=profession)
                if type == 'place':
                    limericks = limericks.filter(place=True)
                elif type == 'name':
                    limericks = limericks.filter(place=False)
                if sort == 'user':
                    limericks_list = limericks.order_by('rank')
                else:
                    limericks_list = limericks.order_by('model_rank')

                request.session['sort'] = sort # remember sorting of table
                request.session['filtered_limericks'] = [l.id for l in limericks_list] # remember list of limericks
        else:
            if sort == 'user':
                limericks_list = Limerick.objects.order_by('rank')
            else:
                limericks_list = Limerick.objects.order_by('model_rank')
            filter_form = FilterForm(initial={'gender':'All','adjective':'All','profession':'All','type':'All'}) # if no filtering applied, show all limericks

        page = request.GET.get('page', 1)
        paginator = Paginator(limericks_list, 10) # split all limericks in pages of 10
        try:
            limericks = paginator.page(page)
        except PageNotAnInteger:
            limericks = paginator.page(1)
        except EmptyPage:
            limericks = paginator.page(paginator.num_pages)
        return render(request, 'limerines/limericks.html', { 'sort' : sort, 'limericks': limericks , 'filter_form': filter_form})

    # detail view to show results and edit capabilities of application
    def detail(request, limerick_id):
        url_name = resolve(request.path).url_name 
        limericks = []
        new_limerick = 0
        originating = 0
        sort = 'user'
        try:
            limericks = request.session['limericks']
        except KeyError:
            pass
        try:
            new_limerick = request.session['new_limerick']
        except KeyError:
            pass
        try:
            originating = request.session['originating']
        except KeyError:
            pass
        try:
            sort = request.session['sort']
        except KeyError:
            pass

        # only limericks that have just been generated can be edited
        if url_name == 'edit' and limerick_id not in limericks: 
            return render(request, 'limerines/pageNotFound.html')
        if url_name == 'result' and limerick_id != new_limerick:
            return render(request, 'limerines/pageNotFound.html')

        if url_name != 'result':
            try:
                del request.session['new_limerick']
            except KeyError:
                pass
        
        limerick = get_object_or_404(Limerick, pk=limerick_id)
        if request.method == "POST":
            if 'upvote' in request.POST: # upvote request, voting directly from limerick
                form = VoteForm(request.POST)
                if form.is_valid():
                    upvote = form.cleaned_data.get('upvote')
                    if upvote == 'true':
                        limerick.votes += 1
                    elif upvote == 'false':
                        limerick.votes -= 1
                    limerick.save()
                    update_rankings() # update raking after voting
                    return render(request, 'limerines/detail.html', {'limericks':limericks, 'limerick':limerick, 'originating':originating, 'sort':sort})
            if 'verse1' in request.POST: # if verse1 in post request, a regeneration reques has been sent
                form = SaveLimerickForm(request.POST)
                print(request.POST)
                if form.is_valid():
                    verse1 = form.cleaned_data.get('verse1'); verse2 = form.cleaned_data.get('verse2')
                    verse3 = form.cleaned_data.get('verse3'); verse4 = form.cleaned_data.get('verse4')
                    verse5 = form.cleaned_data.get('verse5')
                    overse1 = form.cleaned_data.get('overse1'); overse3 = form.cleaned_data.get('overse3')
                    overse4 = form.cleaned_data.get('overse4'); overse5 = form.cleaned_data.get('overse5')[:-1]
                    female = form.cleaned_data.get('female'); place = form.cleaned_data.get('place')
                    adjective = form.cleaned_data.get('adjective'); profession = form.cleaned_data.get('profession')
                    request.session['originating'] = limerick.id 

                    # use the input data to check from which verse the regeneration should start
                    if verse3 != 'hidden' and verse4 != 'hidden' and verse5 != 'hidden':
                        l = Limerick(verse1 = verse1, verse2 = verse2, verse3 = verse3, verse4 = verse4, verse5 = verse5, 
                        female = female, adjective = adjective, profession = profession, place = place)
                        l.get_pronunciation()
                        l.get_perplexity()
                        l.save()
                        update_rankings()
                        request.session['new_limerick'] = l.id
                        return redirect('limerines:result', limerick_id=l.id)
                    if verse3 != 'hidden' and verse4 != 'hidden' and verse5 == 'hidden':
                        text = verse1 + ' ' + verse2 + ' ' + verse3 + ' ' + verse4
                        l = generateFromFourth(text, overse5, adjective, profession, female, place)
                        request.session['new_limerick'] = l.id
                        return redirect('limerines:result', limerick_id=l.id)
                    if verse3 != 'hidden' and verse4 == 'hidden' and verse5 == 'hidden':
                        text = verse1 + ' ' + verse2 + ' ' + verse3
                        l = generateFromThird(text, overse4, overse5, adjective, profession, female, place) 
                        request.session['new_limerick'] = l.id
                        return redirect('limerines:result', limerick_id=l.id)  
                    if verse3 == 'hidden' and verse4 == 'hidden' and verse5 == 'hidden':
                        text = verse1 + ' ' + verse2
                        l = generateFromSecond(text, overse1, overse3, overse4, overse5, adjective, profession, female, place)
                        request.session['new_limerick'] = l.id
                        return redirect('limerines:result', limerick_id=l.id)
        else:
            return render(request, 'limerines/detail.html', {'limericks':limericks, 'limerick':limerick, 'originating':originating, 'sort':sort})

    def generate_limerick(request):
        # delete session before generating a limerick
        try:

limerines/templates/limerines/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" type="text/css" href="{% static 'limerines/style_base.css' %}">
    <div class="banner">
        <div><a class="banner-content" href="{% url 'limerines:index' %}">Limerickation.</a></div>
    </div>
    <body>
    {% block content %}
    {% endblock %}
    </body>
</html>

limerines/templates/limerines/detail.html
{% extends './base.html' %}
{% load static %}
{% block content %}
{% load generate_extras %}

{% get_pair_id limerick as limerick_pair %}
{% get_pair_2_id limerick as limerick_pair2 %}
{% pron_order limerick as pronounciations %}
{% get_place limerick as place %}
{% get_second_verses limerick as second %}
{% get_third_verses limerick as third %}
{% get_fourth_verses limerick as fourth %}
{% get_fifth_verses limerick as fifth %}
{% get_first_verses limerick as first %}
{% get_previous limerick request.path limericks sort request.session.filtered_limericks as previous %}
{% get_next limerick request.path limericks sort request.session.filtered_limericks as next %}
{% get_all_limericks as all_existing_limericks %}
{% random_from_limerick_list all_existing_limericks as random_limerick %}

{{ all_existing_limericks|json_script:"all_limericks" }}
{{ limerick_pair.id | json_script:"limerick-pair" }}
{{ limerick_pair2.id | json_script:"limerick-pair2" }}
{{ limerick.rank | json_script:"limerick-user-rank" }}
{{ limerick.model_rank | json_script:"limerick-model-rank" }}
{{ limerick_pair.rank | json_script:"limerick-pair-user-rank" }}
{{ limerick_pair2.rank | json_script:"limerick-pair2-user-rank" }}
{{ limerick_pair.model_rank | json_script:"limerick-pair-model-rank" }}
{{ limerick_pair2.model_rank | json_script:"limerick-pair2-model-rank" }}
{{ originating | json_script:"originating-id" }}

{% if next %}
    {{ next.id | json_script:"next-lim-id"}}
{% else %}
    {{ 0 | json_script:"next-lim-id"}}
{% endif %}

{% if previous %}
    {{ previous.id | json_script:"previous-lim-id"}}
{% else %}
    {{ 0 | json_script:"previous-lim-id"}}
{% endif %}

<link rel="stylesheet" type="text/css" href="{% static 'limerines/style_results.css' %}">
<script src="{% static 'limerines/results_code.js' %}"></script>

{% if limericks %}
    <input type="hidden" value={{request.path}} id="are-there-limericks">
{% else %}
    <input type="hidden" value={{request.path}}  id="are-there-limericks">
{% endif %}

<div class="container" id="main-container">
    <section class="screen left">
        <div class="limerick-block" id="limerick-block">
            <div class="options" id="options-hidden">
                <div class="hidden">
                    <div><img src="{% static 'limerines/media/gender-icon.png' %}" width=30px></div>
                </div>
            </div>
            <div class="limerick cards" id="original-limerick">
                <div class = "card"  id="card">
                    <div class="front">
                        <div id="original-1">{{limerick.verse1}}</div><br>
                        <div id="original-2">{{limerick.verse2}}</div><br>
                        <div id="original-3">{{limerick.verse3}}</div><br>
                        <div id="original-4">{{limerick.verse4}}</div><br>
                        <div id="original-5">{{limerick.verse5}}</div>              
                    </div>
                    <div class="back" id="card-back">
                        {% if limerick_pair %}
                            {{limerick_pair.verse1}}<br><br>
                            {{limerick_pair.verse2}}<br><br>
                            {{limerick_pair.verse3}}<br><br>
                            {{limerick_pair.verse4}}<br><br>
                            {{limerick_pair.verse5}}<br>  
                        {% else %}
                            {{limerick.verse1}}<br><br>
                            {{limerick.verse2}}<br><br>
                            {{limerick.verse3}}<br><br>
                            {{limerick.verse4}}<br><br>
                            {{limerick.verse5}}<br>  
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="hidden-text" id="temp-card-back">
                {% for verse in pronounciations %}
                    <div class = pron-container1>
                        {% for a, b in verse %}
                            <div class = pron-container2>
                                <div>{{a}}</div>
                                <div class="pron-font">{{b}}</div><br>
                            </div>
                        {% endfor %}    
                    </div>
                {% endfor %}
            </div>
            <div class="hidden-text" id="temp-card-back-pair2">
                {% if limerick_pair2 %}
                    {{limerick_pair2.verse1}}<br><br>
                    {{limerick_pair2.verse2}}<br><br>
                    {{limerick_pair2.verse3}}<br><br>
                    {{limerick_pair2.verse4}}<br><br>
                    {{limerick_pair2.verse5}}<br>            
                {% endif %}
            </div>
            <div class="options" id="options">
                <div><img src="{% static 'limerines/media/pron-icon.png' %}" class = "filter" width=30px id="pron-switch"></div>
                <div><form id="submit-vote" method="post">
                    {% csrf_token %}
                    <div class="vote" id="voting-buttons">
                        <div class="item-hidden">3</div>
                        <div class="item-center">
                            <button type="vote_button" onclick="vote('true')" class="increment up"></button>
                            <button type="vote_button" onclick="vote('false')"  class="increment down"></button>
                        </div>
                        <input type="hidden" name = "upvote" id="action_vote">
                        <input type="hidden" name = "limerick_id" value="{{limerick.pk}}">
                        <div class="item-right">{{limerick.votes}}</div>
                    </div>
                </form></div>
                {% if not place %}
                    <div><img src="{% static 'limerines/media/gender-icon.png' %}" class = "filter" width=30px id="gender-switch"></div>
                    <div><img src="{% static 'limerines/media/place-icon.png' %}" class = "filter" width=30px id="place-switch"></div>
                {% else %}
                    <div><img src="{% static 'limerines/media/male-icon.png' %}" class = "filter" width=30px id="gender-switch"></div>
                    <div><img src="{% static 'limerines/media/female-icon.png' %}" class = "filter" width=30px id="place-switch"></div>
                {% endif %}
            </div>
        </div>
        <div id="navigation-buttons">
            {% if previous %}
                <div class="previous"><a id="previous-limerick" href="{{previous.id}}">&laquo;Previous</a></div>
            {% else %}
                <div class="previous disabled"><a id="previous-limerick" href='#'>&laquo;Previous</a></div>
            {% endif %}
            {% if next %}
                <div class="next"><a id="next-limerick" href="{{next.id}}">Next&raquo;</a></div>
            {% else %}
                <div class="next disabled"><a id="next-limerick" href='#'>Next&raquo;</a></div>
            {% endif %}
        </div>
        <div id="back-button"><a id="originating-limerick" href="#">Back to Original</a></div>
        <img src="{% static 'limerines/media/edit-icon.png' %}" width=20px class="edit-filter" onclick="buttonClick()" id="edit-button">
        <a href="{% url 'limerines:limericks' %}" class="limericks-back" id="back-to-limericks">Back to Limericks</a>
    </section>
    <section class="screen right">
        <div class="vline"></div>
        <div class="limerick-block-edit">
            <div id="notification"></div>
            <div class="limerick">
                <div class="select_filter" id="verse1-option">
                    <div disabled class="default_option" id="verse1-current-parent">
                        <div id="verse1-current-selection">{{limerick.verse1}}</div>
                    </div>
                    <ul class="select_ul" id="verse1-list">
                        {% for verse in first %}
                            <li>{{verse}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="select_filter" id="verse2-option">
                    <div class="default_option" id="verse2-current-parent">
                        <div id="verse2-current-selection">{{limerick.verse2}}</div>
                    </div>
                    <ul class="select_ul" id="verse2-list">
                        {% for verse in second %}
                            <li>{{verse}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="select_filter" id="verse3-option">
                    <div class="default_option" id="verse3-current-parent">
                        <div id="verse3-current-selection">{{limerick.verse3}}</div>
                    </div>
                    <ul class="select_ul" id="verse3-list">
                        {% for verse in third %}
                            <li>{{verse}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="select_filter" id="verse4-option">
                    <div class="default_option" id="verse4-current-parent">
                        <div id="verse4-current-selection">{{limerick.verse4}}</div>
                    </div>
                    <ul class="select_ul" id="verse4-list">
                        {% for verse in fourth %}
                            <li>{{verse}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="select_filter" id="verse5-option">
                    <div class="default_option" id="verse5-current-parent">
                        <div id="verse5-current-selection">{{limerick.verse5}}</div>
                    </div>
                    <ul class="select_ul" id="verse5-list">
                        {% for verse in fifth %}
                            <li>{{verse}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <form id = "new-limerick-form" method="post">
            {% csrf_token %}
            <input type="hidden" name="verse1" id="new-verse1">
            <input type="hidden" name="verse2" id="new-verse2">
            <input type="hidden" name="verse3" id="new-verse3">
            <input type="hidden" name="verse4" id="new-verse4">
            <input type="hidden" name="verse5" id="new-verse5">
            <input type="hidden" name="overse3" id="o-verse3">
            <input type="hidden" name="overse1" id="o-verse1">
            <input type="hidden" name="overse4" id="o-verse4">
            <input type="hidden" name="overse5" id="o-verse5">
            <input type="hidden" name="female" value={{limerick.female}}>
            <input type="hidden" name="place" value={{limerick.place}}>
            <input type="hidden" name="adjective" value = {{limerick.adjective}}>
            <input type="hidden" name="profession" value = {{limerick.profession}}>
            <div class="generate" id="generate-button"><button disabled onclick = "loadingScreen()">Generate</button></div>
            <div class="save" id="save-button"><button disabled onclick="loadingScreen()">Save</button></div>
          </form>
        <!--<div class="select_filter" id="gender_option">
            <ul class="default_option" id="gender_current_selection_parent">
                <li id="gender_current_selection">{{filter_form.gender.value}}</li>
            </ul>
            <ul class="select_ul" id="gender_list">
              {% for x,y in filter_form.fields.gender.choices %}
                <li>{{x}}</li>
              {% endfor %}
            </ul>
          </div>-->
    </section>
</div>

<div class="loading-screen" id="loading-screen">
    <div class="limerick-random">
        {% if random_limerick %}
        <h2>Your results will be ready soon, in the meantime enjoy these limericks!</h2>
        <div class="table-row">
            <div class="limerick-text" id="current-random-limerick">
                <div id="random-verse1">{{random_limerick.0}}</div>
                <div id="random-verse2">{{random_limerick.1}}</div>
                <div id="random-verse3">{{random_limerick.2}}</div>
                <div id="random-verse4">{{random_limerick.3}}</div>
                <div id="random-verse5">{{random_limerick.4}}</div>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="loader"></div>
</div>

<img src="{% static 'limerines/media/trophy-icon.png' %}" width=35px onclick="openRanking()" id="score-button">
<div id="rankings" class="sidepanel">
    <a href="javascript:void(0)" class="closebtn" onclick="closeRanking()">&times;</a>
    <label>User Rank</label>
    <div class="score" id="user-rank-display">{{limerick.rank}}/{{all_existing_limericks|length}}</div>
    <br>
    <label>Model Rank</label>
    <div class="score" id="model-rank-display">{{limerick.model_rank}}/{{all_existing_limericks|length}}</div>
</div>

{% endblock %}

limerines/templates/limerines/errorGeneration.html
{% extends './base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'limerines/style_pageNotFound.css' %}">
<h2>Could not generate limericks at this time</h2>
<a class="button" href="{% url 'limerines:generate' %}">Try again</a>
{% endblock %}

limerines/templates/limerines/generate.html
{% extends './base.html' %}
{% load static %}
{% block content %}
{% load generate_extras %}

{% get_adjective_professions as adj_prof_dict %}
{% get_all_limericks as all_existing_limericks %}
{% random_from_limerick_list all_existing_limericks as random_limerick %}

{{ all_existing_limericks|json_script:"all_limericks" }}
{{ adj_prof_dict|json_script:"adjprof-data" }}
{% if loading and next_id %}
    {{ loading|json_script:"loading" }}
    {{ next_id|json_script:"next_id" }}
{% else %}
    {{ "no-loading"|json_script:"loading" }}
    {{ 0|json_script:"next_id" }}
{% endif %}

<link rel="stylesheet" type="text/css" href="{% static 'limerines/style_generate.css' %}">
<script src="{% static 'limerines/code.js' %}"></script>
<div id="container">
    <form id="limerick-generation" method="post">
        {% csrf_token %}
        <div class="block">
            <div class="wrapper">
                <div class="title"> First choose an adjective:</div>
                    <div class="select_wrap" id="adjective_option">
                        <ul class="default_option" id="adjective_current_selection_parent">
                            <li id="adjective_current_selection">{{form.adjective.initial}}</li>
                        </ul>
                        <ul class="select_ul" id="adjective_list">
                            {% for x,y in form.fields.adjective.choices %}
                                <li>{{x}}</li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
            <br>
            <div class="wrapper">
                <div class="title"> Now choose a profession:</div>
                    <div class="select_wrap" id="profession_option">
                        <ul class="default_option" id="profession_current_selection_parent">
                            <li id="profession_current_selection">{{form.profession.initial}}</li>
                        </ul>
                        <ul class="select_ul" id="profession_list">
                            {% for x,y in form.fields.profession.choices %}
                                <li>{{x}}</li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
            <br>
            <input id="random_selection" class="button" type="button" value="Random">
            <br>
            <input id="submit_form" class="button" type="button" value="Best Limerick" onclick="sendGenerationForm('multiple')">
            <br>
            <input id="submit_single_form" class="button" type="button" value="Quick Limerick" onclick="sendGenerationForm('single')">
            <input type="hidden" name="adjective" id="adjective_selection">
            <input type="hidden" name= "profession" id="profession_selection">
            <input type="hidden" name= "kind" id="generation_kind">
        </div>
    </form>
</div>
<div class="loading-screen" id="loading-screen">
    <div class="limerick-random">
        {% if random_limerick %}
        <h2>Your results will be ready soon, in the meantime enjoy these limericks!</h2>
        <div class="table-row">
            <div class="limerick-text" id="current-random-limerick">
                <div id="random-verse1">{{random_limerick.0}}</div>
                <div id="random-verse2">{{random_limerick.1}}</div>
                <div id="random-verse3">{{random_limerick.2}}</div>
                <div id="random-verse4">{{random_limerick.3}}</div>
                <div id="random-verse5">{{random_limerick.4}}</div>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="loader"></div>
</div>
{% endblock %}

limerines/templates/limerines/index.html
{% extends './base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'limerines/style_index.css' %}">
<script src="{% static 'limerines/index_code.js' %}"></script>

<div class="head">
    <h1 id="welcome"></h1>
    <div class="button-container fadeOut" id="buttons">
        <a href="{% url 'limerines:limericks' %}" class="button"> View Limericks</a>
        <a href="{% url 'limerines:generate' %}" class="button"> Generate Limericks</a>
    </div>
</div>
{% endblock %}

limerines/templates/limerines/pageNotFound.html
{% extends './base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'limerines/style_pageNotFound.css' %}">
<h2>Page not found.</h2>
{% endblock %}